"""Initial migration

Revision ID: 369d05ea2a69
Revises: 
Create Date: 2024-12-18 22:29:13.643516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '369d05ea2a69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.Column('grade_level', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_library_grade_level'), ['grade_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_library_title'), ['title'], unique=False)

    op.create_table('tutor_video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=64), nullable=False),
    sa.Column('topic', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tutor_video', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tutor_video_subject'), ['subject'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('grade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=64), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grade_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_grade_user_id'), ['user_id'], unique=False)

    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=16), nullable=False),
    sa.Column('lesson_name', sa.String(length=128), nullable=False),
    sa.Column('start_time', sa.String(length=8), nullable=True),
    sa.Column('end_time', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_user_id'))

    op.drop_table('schedule')
    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grade_user_id'))
        batch_op.drop_index(batch_op.f('ix_grade_timestamp'))

    op.drop_table('grade')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('tutor_video', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tutor_video_subject'))

    op.drop_table('tutor_video')
    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_title'))
        batch_op.drop_index(batch_op.f('ix_library_grade_level'))

    op.drop_table('library')
    # ### end Alembic commands ###
